level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO

server:
  port: 8025

ribbon:
  eureka:
    enabled: true

zuul: # those values must be configured depending on the application specific needs
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  ##        connect-timeout-millis: 70000
  ##        socket-timeout-millis: 70000
  semaphore:
    max-semaphores: 500
  prefix: /api #slash before and after
  strip-prefix: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

feign:
  hystrix:
    enabled: true


management:
  security:
    roles: SYSADMIN
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

eureka:
  instance:
    appname: gateway-api
    instanceId: ${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active}
      version: ${info.project.version}
  client:
    client:
      enabled: true
      healthcheck:
        enabled: true
      fetch-registry: true
      register-with-eureka: true
      instance-info-replication-interval-seconds: 10
      registry-fetch-interval-seconds: 10

spring:
  application:
    name: gateway-api
  jackson:
    serialization:
      write_dates_as_timestamps: false
  main:
    allow-bean-definition-overriding: true

