level:
  ROOT: DEBUG
  org.springframework.web: DEBUG
  liquibase: INFO

server:
  port: 8025
  servlet:
    session:
      persistent: false

ribbon:
  eureka:
    enabled: true
  readTimeout: 60000


zuul: # those values must be configured depending on the application specific needs
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  #        connect-timeout-millis: 70000
  #        socket-timeout-millis: 70000
  semaphore:
    max-semaphores: 500
  sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  endpoints:
    web:
      base-path: /management

eureka:
  instance:
    appname: gateway-api
    instanceId: ${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active}
      version: ${info.project.version}
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

spring:
  application:
    name: gateway-api
  jackson:
    serialization:
      write_dates_as_timestamps: false
  main:
    allow-bean-definition-overriding: true

#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /v3/api-docs